### ISSUE TITLE
Adapter Logs (spez. Javascript)

### ISSUE THREAD

**Issue by marcelk1101** [mcuiobroker/docuJarvis#14]
Im AdapterLog Widget wird als Ausgabe der komplette Pfad inklusive dem ausgeführten Script angezeigt. Mein Wunsch wäre nur das Ergebnis anzeigen/filtern zu lassen.

**Comment by mcuiobroker** [comment]
Ist ab der v3.1.4-beta.6 möglich.

**Comment by marcelk1101** [comment]
Super. Wo finde ich eine kleine Anleitung dazu?

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/v3-fuer-einsteiger/module/adapterlog-v3.1.x
