### ISSUE TITLE
Popup States ausblenden wenn Datenwert = "false"

### ISSUE THREAD

**Issue by tschortschde** [mcuiobroker/docuJarvis#27]
Hallo,
ich würde gerne die States im Popup filtern bzw. ausblenden?
Ich möchte gerne die geschlossenen Fenster im Popup nicht anzeigen...
Kann das umgesetzt werden?
![Screenshot 2023-03-24 195339](https://user-images.githubusercontent.com/11274233/227625861-acc4ffcd-3d39-4ee6-9a27-575ac4e3664a.jpg)
VG

**Comment by mcuiobroker** [comment]
Als isssue unter Jarvis anlegen nicht hier in der Doku.
https://github.com/Zefau/ioBroker.jarvis/issues

**Comment by tschortschde** [comment]
Ich habe es im Gerät unter dem BodyStil so gelöst:
{
  "{Büro-Fensterzustand-Status_senden}=false": {
    "display": "none !important"
  }
}
