### ISSUE TITLE
{val} im Label nutzen

### ISSUE THREAD

**Issue by Mephisto090** [mcuiobroker/docuJarvis#45]
Hej,

ist es irgendwie möglich {val} im Label zu nutzen, sodass der Datenpunkt ausgegeben wird?

![image](https://github.com/mcuiobroker/docuJarvis/assets/85995176/907546b4-041c-4969-9061-f33d2af74fde)

![image](https://github.com/mcuiobroker/docuJarvis/assets/85995176/a5f6fdf0-42cc-415d-8a32-a26210506dc6)

VG

**Comment by mcuiobroker** [comment]
Kannst es versuchen mit 
```
{"default":"{val}"}

**Comment by Mephisto090** [comment]
das klappt. Danke
